version: '3'
services:
  vault:
    build: .
    container_name: vault
    ports:
      - "8200:8200"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vault
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
