

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-api
spec:
  provider:
    vault:
      server: "http://192.168.15.11:8200"
      path: "dev"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-policy-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-api
    kind: ClusterSecretStore
  target:
    name: dev-pass
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: dev/pass
        property: user
    - secretKey: pass
      remoteRef:
        key: dev/pass
        property: pass
